name: CICD

on:
  push:
    branches: [main, master, Oscar-Branch]

jobs:
  build:
    runs-on: ubuntu-latest # Remove brackets (not needed)
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x # Align with package.json "engines"

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: meal-health-app
          publish-profile: ${{ secrets.HERBAL_LIFE_SECRET }}
          package: .
